# student_score = {}
# for name in range(2):
#     enter = input("Enter your name: ")
#     score = 0
#     question = ["Who is the president of Nigeria?", "SQI is which School?"]
#     answer = ["President Muhammad Buhari", "Business School"]
#     for i,  que in enumerate(question):
#         print(que)
#         ans = input("Enter your answer: ")
#         correct = answer[i]
#         if correct == ans:
#             print("You're right!")
#             score += 5
#         else:
#             print("You are wrong.")
#     student_score[enter] = score

# print(student_score)
# max_score_key = max(student_score, key=student_score.get)

# print("The student that has the Maximum score is: ", max_score_key)
"""

enumerate(question) - The enumerate() function is a built-in Python function that takes an iterable 
(in this case, the question list) and returns an iterator that produces pairs of elements along 
with their index. Each pair consists of an index and the corresponding element from the iterable.
In our case, enumerate(question) will produce pairs like (0, "Who is the president of Nigeria?"), 
(1, "SQI is which School?"), where the first element in the pair is the index (starting from 0) 
and the second element is the question itself.
for i, que in enumerate(question): - This is a for loop that iterates over the pairs generated by enumerate(question). 
The loop variable i represents the index, and que represents the corresponding question.
On each iteration of the loop, i will take the value of the index, and que will take the value of the question. 
For example, in the first iteration, i will be 0 and que will be "Who is the president of Nigeria?". 
In the second iteration, i will be 1 and que will be "SQI is which School?".
This line allows you to loop over the question list while also having access to the index and the 
corresponding question itself within the loop body. This is useful if you need to perform any operations or 
comparisons based on the index or if you need to access both the index and the question simultaneously.

"""

#NESTED WHILE LOOP

# all_customer = {}
# i = 1
# while i <= 4:
#     customer = []
#     info = ['firstName', 'lastName', 'age', 'phone']
#     print("Enter customer " + str(i) + " information")
#     con = input("press 'enter' to continue or 'end' to quit ")
#     while con == 'end':
#         break
#     if con == 'enter': 
#         for fo in info:
#             inf = input("Enter your " + fo + ": ")
#             customer.append(inf)
        
#         while len(customer[3]) < 11: #You don't have to check if customer[3], only len(customer[3]) 
#             print("Phone number cannot be less than 11 digits")
#             new = input("Enter your phone number again: ")
#             customer[3] = new  # Replace the incorrect phone number
        
#         print(customer)
      
#     all_customer["customer" + str(i)] = customer
#     i += 1
#     while con == 'end':
#         all_customer['customer' + str(i)] = customer
#         break
#     print(all_customer)

# else:
#     print(all_customer)

# print(all_customer)
# PYTHON FUNCTION IS A NAMED SECTION OF A CODE THAT PERFORMS A SPECIFIC TASK.
# IT IS A BLOCK OF CODE WHICH RUNS WHEN IT IS CALLED.

# WHY DO WE USE function
# To avoid repetition of codes which makes our program slow
# for easy readability 
# for code useability
# for easy debugging

# def add():
#     val1 = 20
#     val2 = 25
#     print (val1 + val2)

# types of function
# built-in function
# input()
# .strip()
# .lower()
# print()
# split()
# val1 = int(input("Enter first value: "))
# val2 = int(input("Enter second value: "))
# num1 = int(input("What is your first value? "))
# num2 = int(input("What is your second value? "))
# def operation():
#     op = input("Choose operation to perform: ")
#     if op == "1":
#         addition()
#     elif op == "2":
#         subtraction()
#     elif op == "3":
#         multiplication()
#     elif op == "4":
#         division()
#     else:
#         print("Unknown operation")
#         operation()

# def addition():
#     print(num1 + num2)


# def subtraction():
#     print(f" your score is {num1 - num2}")

# def multiplication():
#     print(f" your score is {num1* num2}")

# def division():
#     print(f" your score is {num1 / num2}")

# operation()

"""
Assignment
Write a python program that will ask user to choose subject to do exam, you are to have 5 subjects with at least
5 questions in each of the subjects, when user is done, the subject and the score for the subject should be 
stored in a dictionary, print out the subject with the maximum score.
Submission is tomorrow
"""

result = {}
def exam():    
    for i in range(2):
        student = input("Enter your student name ")
        print("NOTE!! You only have 5 trials. One for each subject")
        for i in range(5):
            subject = input("Enter the subject ").lower()
            if subject == "mathematics":
                maths(subject)
            elif subject == "english":
                english(subject)
            elif subject == "physics":
                physics(subject)
            elif subject == "geography":
                geo(subject)
            elif subject == "chemistry":
                chemistry(subject)
            else:
                print("Choose from the following options: Mathematics, English, Physics, Geography, Chemistry. Start again")
                exam()
                break
        print(result)
        print(f"{student} scored the highest in {min(result)} after writing {len(result)} subject(s)")

def maths(subject):
    score = 0
    question = ["Random Question", "Some Question"]
    options = ["a -- option", "b -- option"]
    answer = ["b", "a"]
    for i in range(2):
        print(question[i])
        print(options[i])
        user_ans = input("Enter your answer ")
        if user_ans == answer[i]:
            print("Correct")
            score += 5
        else:
            print("wrong")
    result.update({subject:score})


def english(subject):
    score = 0
    question = ["Random Question", "Some Question"]
    options = ["a -- option", "b -- option"]
    answer = ["b", "a"]
    for i in range(2):
        print(question[i])
        print(options[i])
        user_ans = input("Enter your answer ")
        if user_ans == answer[i]:
            print("Correct")
            score += 5
        else:
            print("wrong")
    result.update({subject:score})


def physics(subject):
    score = 0
    question = ["Random Question", "Some Question"]
    options = ["a -- option", "b -- option"]
    answer = ["b", "a"]
    for i in range(2):
        print(question[i])
        print(options[i])
        user_ans = input("Enter your answer ")
        if user_ans == answer[i]:
            print("Correct")
            score += 5
        else:
            print("wrong")
    result.update({subject:score})


def geo(subject):
    score = 0
    question = ["Random Question", "Some Question"]
    options = ["a -- option", "b -- option"]
    answer = ["b", "a"]
    for i in range(2):
        print(question[i])
        print(options[i])
        user_ans = input("Enter your answer ")
        if user_ans == answer[i]:
            print("Correct")
            score += 5
        else:
            print("wrong")
    result.update({subject:score})


def chemistry(subject):
    score = 0
    question = ["Random Question", "Some Question"]
    options = ["a -- option", "b -- option"]
    answer = ["b", "a"]
    for i in range(2):
        print(question[i])
        print(options[i])
        user_ans = input("Enter your answer ")
        if user_ans == answer[i]:
            print("Correct")
            score += 5
        else:
            print("wrong")
    result.update({subject:score})




        
exam()